services:
  postgres:
    image: postgres:15-alpine  # Version de PostgreSQL
    container_name: postgres-container
    restart: always
    env_file:
      - api/.env
    ports:
      - "5432:5432"             # Expose le port 5432 pour PostgreSQL
    volumes:
      - PostgreSQLdb:/var/lib/postgresql/data # Stockage des données
      - ./back-end/db-scripts:/docker-entrypoint-initdb.d/ # Chemin des scripts SQL pour l'initialisation de la base de données

  node_app:
    build: ./api
    container_name: node-app-container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./api:/usr/src/app
    env_file:
      - api/.env
    environment:
      DATABASE_URL: ${DATABASE_URL} # URL de la base de données

volumes:
  PostgreSQLdb:
